### PR TITLE
[hotfix][tests] Fix occasional pipeline E2e testcases failure

### PR DESCRIPTION
**Pull request by yuxiqian**
Currently, `MySqlE2eITCase`'s result verification strategy is as follows: First, it keeps waiting until the last expected record received, then fetch all outputs at once and check if all expected records present.

The problem is data insertion events aren't guaranteed in sequence even with single parallelism, since MySQL INSERT statements are not strictly in order. So, any records come after the "last expected record" will not be checked, causing testcases to fail.

A failed test job: https://github.com/yuxiqian/flink-cdc/actions/runs/9015394982/job/24769924116?pr=12

This PR changes the verification logic by waiting for each expected record in sequence to fix this rarely happening CI failure.

### CODE REVIEW

**Comment by yuxiqian** [comment]
cc @lvyanquan

**Comment by lvyanquan** [comment]
LGTM, waiting for CI pass.

**Review by lvyanquan — APPROVED** [review]

**Comment by yuxiqian** [comment]
Could @PatrickRen help take a look? Thanks!

**Comment by yuxiqian** [comment]
Fixed in #3348.

**Pull request closed without merging**
