### PR TITLE
[docs]Change host to host name in configuration for readme

### PR DESCRIPTION
**Pull request by cjj2010**
Change host to host name in configuration for readme

### CODE REVIEW

**Comment by gtk96** [comment]
https://ververica.github.io/flink-cdc-connectors/master/content/overview/cdc-pipeline.html    
This page is the same error

**Comment by cjj2010** [comment]
> https://ververica.github.io/flink-cdc-connectors/master/content/overview/cdc-pipeline.html This page is the same error

I have made the necessary modifications. Thank you for your reminder

**Comment by GOODBOY008** [comment]
@cjj2010 There are still some need to fix.
企业微信截图_17096889368904

**Comment by cjj2010** [comment]
> @cjj2010 There are still some need to fix. 企业微信截图_17096889368904

The above searches have just been corrected

**Comment by cjj2010** [comment]
> @cjj2010 There are still some need to fix. 企业微信截图_17096889368904

The above searches have just been corrected

**Comment by cjj2010** [comment]
cc @GOODBOY008

**Comment by PatrickRen** [comment]
@cjj2010 Thanks for the PR! Could you rebase the latest master as we refactored the README and docs recently

**Comment by cjj2010** [comment]
> Could you

Complete rebase now

**Comment by gtk96** [comment]
@cjj2010 Can you only keep your own changes to submit?

**Comment by cjj2010** [comment]
The document has been repaired

**Pull request closed without merging**
