### PR TITLE
[FLINK-36024] Handle BinaryLogClient exceptions when searching for starting binlog offset

### PR DESCRIPTION
**Pull request by whhe**

### CODE REVIEW

**Comment by leonardBang** [comment]
@ruanhang1993 @PatrickRen Would you like to take a look this PR when you have time?

**Comment by whhe** [comment]
It's weird that I can't reopen this pr.

**Comment by leonardBang** [comment]
I cannot too, weird... @yuxiqian could you help with this case ?

**Comment by leonardBang** [comment]
I cannot too, weird... @yuxiqian could you help with this case ?

**Comment by whhe** [comment]
> I cannot too, weird... @yuxiqian could you help with this case ?

I have created a new pr https://github.com/apache/flink-cdc/pull/3730

**Comment by yuxiqian** [comment]
I believe there's a GitHub limitation as mentioned in https://github.com/actions/stale/issues/345 and [here](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github). Basically issues / PRs closed by collaborators (including authorized bots) could not be reopened without access to the repository.

**Pull request closed without merging**
