### PR TITLE
[mysql] support for transaction metadata events

### PR DESCRIPTION
**Pull request by rashminpatel123**
This contribution is about allowing transaction metadata events to flow in the output.

### CODE REVIEW

**Comment by rashminpatel123** [comment]
@leonardBang Can you review this PR or assign a reviewer ?

**Comment by rashminpatel123** [comment]
cc: @GOODBOY008

**Comment by leonardBang** [comment]
Thanks @rashminpatel123 for the contribution, sorry for the late reply due to my vacation, I'll add this PR to my TODO list.

**Comment by GeeinHub** [comment]
Hello, how about this issue?
with
        Properties dbzProperties = new Properties();
        dbzProperties.setProperty("provide.transaction.metadata","true");

there's transaction info in data change record, but still no transaction info record in output?

**Comment by yuxiqian** [comment]
Hi @rashminpatel123, sorry for the delay of this PR. Could you please rebase it to latest `master` branch since there’s been lots of changes in Flink CDC repo since your original commit? Kindly reminder that `com.ververica.cdc.connectors.mysql` package has been moved to `org.apache.flink.cdc.connectors.mysql`.

Thanks for your contribution!

**Pull request closed without merging**
