### PR TITLE
[mongodb] Add lookup option to IncrementalSource for mongodb

### PR DESCRIPTION
**Pull request by vanliu-tx**

### CODE REVIEW

**Comment by vanliu-tx** [comment]
@Jiabao-Sun could you help to review this PR?

**Comment by Jiabao-Sun** [comment]
Thanks @vanliu-tx for this contribution.
But for Flink SQL, full document is always needed. 
I think we only need to open it in the Stream API, what do you think?

**Comment by vanliu-tx** [comment]
> Thanks @vanliu-tx for this contribution. But for Flink SQL, full document is always needed. I think we only need to open it in the Stream API, what do you think?

sure, this option is only need in Stream API.

**Comment by vanliu-tx** [comment]
@Jiabao-Sun could you help to review again? I added some docs for the config option.

**Comment by yuxiqian** [comment]
Hi @vanliu-tx, thanks for your contribution! Could you please rebase this PR with latest `master` branch? You may need to rename some packages from `com.ververica.cdc` to `org.apache.flink.cdc`.

cc @Jiabao-Sun

**Pull request closed without merging**
