### PR TITLE
[tidb-cdc]fix too many fields cause the value to be NULL

### PR DESCRIPTION
**Pull request by MengXiangDing**
fix issues：https://github.com/ververica/flink-cdc-connectors/issues/1883

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@mxd-321 Thanks for your contribution. Please format code by maven `spotless:apply`. Can you add unit test to check this fix is worked?

**Comment by mxd-321** [comment]
@GOODBOY008 Hi，I executed "mvn spotless:apply" and "mvn spotless:check"

**Comment by GOODBOY008** [comment]
> @GOODBOY008 Hi，I executed "mvn spotless:apply" and "mvn spotless:check"

https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=2691&view=logs&j=668ee87f-c790-5715-ed85-7ccae79a5a1f&t=24e740b6-f920-55b3-3442-aec852868a00&l=1117
@mxd-321 ,Maven checkstyle failed, you can run local util passed.

**Comment by mxd-321** [comment]
@GOODBOY008  Hi, there are still a few "ci" that have not passed. Can you help me take a look? And review the code. Thank you !

**Comment by GOODBOY008** [comment]
> @GOODBOY008 Hi, there are still a few "ci" that have not passed. Can you help me take a look? And review the code. Thank you !

Unit test failed. https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=2695&view=logs&j=7f9f9f19-4e92-50a8-2f68-2b1038ea61d1&t=a202a4b7-0f62-5127-83cb-4dfa74d97257&l=752

**Pull request closed without merging**
