### PR TITLE
[cdc][mysql]Mysql supports modify column schema changes

### PR DESCRIPTION
**Pull request by ChengJie1053**
Mysql supports modify column schema changes

ALTER TABLE `app_db`.`shipments_copy1` 
MODIFY COLUMN `text_column` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL AFTER `string_column`

image

image

image

### CODE REVIEW

**Comment by yuxiqian** [comment]
Duplicate of #3352

**Comment by ChengJie1053** [comment]
Ok, I didn't know that this requirement had been completed

**Comment by yuxiqian** [comment]
Nevermind, thanks for your contribution!

**Comment by ChengJie1053** [comment]
Ok, thank you. I'm new to this project. Are there any beginner tasks I can complete

**Comment by yuxiqian** [comment]
Sure! The team is currently working on the upcoming 3.2 release, and seems there's still much reported but unassigned tickets in [Jira](https://issues.apache.org/jira/browse/FLINK-35545?jql=project%20%3D%20FLINK%20AND%20fixVersion%20%3D%20cdc-3.2.0). Feel free to comment there if you'd like to take some :)

**Comment by ChengJie1053** [comment]
Ok, thank you

**Pull request closed without merging**
