### PR TITLE
[FLINK-34664][cdc] Add .asf.yaml file

### PR DESCRIPTION
**Pull request by PatrickRen**
This pull request adds `.asf.yaml` file for configuring project descriptions, merge behaviors and Jira auto-links.

### CODE REVIEW

**Comment by whhe** [comment]
I'm not familiar with this, just for curiosity, what is the 'labels' used for.

**Review by leonardBang — APPROVED** [review]
Thanks @PatrickRen for the contribution, LGTM, let's merge it and see how the About page changed.

**Comment by leonardBang** [comment]
> I'm not familiar with this, just for curiosity, what is the 'labels' used for.

The label should be the topic of Github repo About page

**Comment by whhe** [comment]
> > I'm not familiar with this, just for curiosity, what is the 'labels' used for.
> 
> The label should be the topic of Github repo About page

Thanks for the explanation, it sounds very cool. Please go on the merging.

**Pull request merged**
