### PR TITLE
[FLINK-35121][pipeline-connector][cdc-base] CDC pipeline connector provide ability to verify requiredOptions and optionalOptions

### PR DESCRIPTION
**Pull request by loserwang1024**
CDC pipeline connector provide ability to verify requiredOptions and optionalOptions, nor will be  hard to handle compatibility later。

### CODE REVIEW

**Comment by yuxiqian** [comment]
Seems there's some overlap between this PR and #3382, @loserwang1024 mind if I cherry pick your commit?

**Review by morazow — CHANGES_REQUESTED** [review]
Thanks @loserwang1024 👍 

Minor suggestion from side to use the `assertj` assertion of instance of checks

**Comment by loserwang1024** [comment]
>  @loserwang1024 mind if I cherry pick your commit?

Just do it.

**Comment by Jiabao-Sun** [comment]
Closed by #3382

**Pull request closed without merging**
