### PR TITLE
[hotfix][cdc][docs] Supplementary answer to the Mysql CDC Q15 question

### PR DESCRIPTION
**Pull request by PONYLEE**
Supplementary answer to the [Mysql CDC Q15] question

### CODE REVIEW

**Comment by PONYLEE** [comment]
@lvyanquan  Would you help to have a look at this?

**Comment by PONYLEE** [comment]
@leonardBang  PTAL

**Review by leonardBang — APPROVED** [review]
Thanks @PONYLEE for the contribution, I've tested the regex pattern, LGTM, wait the doc CI

**Comment by PONYLEE** [comment]
@leonardBang When will the commit be merged, please?

**Comment by leonardBang** [comment]
> Thanks @PONYLEE for the contribution, I've tested the regex pattern, LGTM, wait the doc CI

Merged, thanks for your contribution.

**Pull request merged**
