### PR TITLE
[FLINK-36572][pipeline-connector][starrocks] Fix the issue that the local time zone is wrongly set

### PR DESCRIPTION
**Pull request by herunkang2018**

### CODE REVIEW

**Review by lvyanquan — APPROVED** [review]
LGTM.

**Comment by herunkang2018** [comment]
@PatrickRen @ruanhang1993 Could you please help to review this? Thanks very much.

**Review by lvyanquan — APPROVED** [review]

**Review by leonardBang — APPROVED** [review]
Thanks @herunkang2018 for the contribution and @lvyanquan for the review, +1

**Comment by herunkang2018** [comment]
@leonardBang Could you help to merge this request? Thanks very much.

**Comment by leonardBang** [comment]
> _ No description provided. _

CI passed, will merge soon, @herunkang2018 Thanks for your contribution and the PR description is welcome for next contributions.

**Comment by yuxiqian** [comment]
Could @herunkang2018 please backport it to release-3.2 branch?

**Comment by herunkang2018** [comment]
@yuxiqian I will backport it to release-3.2 branch soon.

**Comment by herunkang2018** [comment]
The backport PR is ready: https://github.com/apache/flink-cdc/pull/3733

**Pull request merged**
