### PR TITLE
[FLINK-35432]Support catch modify event for the mysql.

### PR DESCRIPTION
**Pull request by hk-lrzy**
Doris & StarRocks are not support the `UpdateTypeEvent` right now, So should i need change the implement for Doris and Starrocks to ignore the UpdateTypeEvent to keep job healthy?

### CODE REVIEW

**Comment by yuxiqian** [comment]
Hi @hk-lrzy, thanks for your contribution! Missing of `MODIFY COLUMN` in MySQL DDL parsing is a glitch and needs to be resolved.

As for downstream sink support, I'm currently working on FLINK-35242 to provide "Partial Schema Apply" ability. Feel free to leave your comments since it's still in very early stage.

**Review by yuxiqian — APPROVED** [review]
Thanks for the patch! LGTM

**Comment by yuxiqian** [comment]
> @yuxiqian can you help me trigger cicd?

Sorry I do not have such privilege, either. You may create a PR to your fork repository (e.g. from `hk-lrzy:FLINK-35432` to `hk-lrzy:master`) to run CI on your own repository.

**Comment by yuxiqian** [comment]
Could @ruanhang1993 take a look on this?

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Pull request merged**
