### PR TITLE
[FLINK-34681][cdc][doc] add standalone.md under deployment directory.

### PR DESCRIPTION
**Pull request by lvyanquan**
add standalone.md

### CODE REVIEW

**Review by loserwang1024 — COMMENTED** [review]
Please also add standalone.md which is an empty file in content.zh

**Comment by lvyanquan** [comment]
It has already been added https://github.com/apache/flink-cdc/blob/master/docs/content.zh/docs/deployment/standalone.md

**Comment by lvyanquan** [comment]
> Please also add standalone.md which is an empty file in content.zh

I will create a following PR to support Chinese language with this document and the previously merged documents.

**Review by PatrickRen — APPROVED** [review]
@lvyanquan Thanks for the PR! LGTM.

**Pull request merged**
