### PR TITLE
[mysql-cdc] Fix the hung up of snapshot phase when reuse binaryLogClient

### PR DESCRIPTION
**Pull request by lzshlzsh**
Because callback( [eventListeners](https://github.com/shyiko/mysql-binlog-connector-java/blob/dd710a5466381faa57442977b24fceff56a0820e/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L142) and lifecycleListeners) of BinaryLogClient is a list, and BinaryLogClient may reuse (see [MySqlSplitReader#checkSplitOrStartNext](https://github.com/ververica/flink-cdc-connectors/blob/eb5610c29bf6deee9abc1f5a28208f0a0b02b99a/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSplitReader.java#L139))，when multiple snapshotSplits are submitted to a [SnapshotSplitReader](https://github.com/ververica/flink-cdc-connectors/blob/eb5610c29bf6deee9abc1f5a28208f0a0b02b99a/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSplitReader.java#L159), the callback list contains already processed snapshotSplits's [MySqlBinlogSplitReadTask#handleEvent](https://github.com/ververica/flink-cdc-connectors/blob/eb5610c29bf6deee9abc1f5a28208f0a0b02b99a/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/MySqlBinlogSplitReadTask.java#L84)。When a binlog event arrives, the processed snapshot's callbacks are called and causes the current snapshot's BackfillBinlogReadTask's [execute function](https://github.com/ververica/flink-cdc-connectors/blob/eb5610c29bf6deee9abc1f5a28208f0a0b02b99a/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java#L158) end before get the BINLOG_END watermark event. So the snapshot phase hangs.

The following is the log of our online environment, we can see muliple MySqlStreamingChangeEventSource(super calss of MySqlBinlogSplitReadTask) callbacks of different snapshotSplits.
```
io.debezium.connector.mysql.MySqlStreamingChangeEventSource - XXX: eventListeners(7): com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@61540cca,com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@352b5758,io.debezium.connector.mysql.MySqlStreamingChangeEventSource$$Lambda$1014/1247290871@703f0cf,io.debezium.connector.mysql.MySqlStreamingChangeEventSource$$Lambda$1015/190751860@5a253136,io.debezium.connector.mysql.MySqlStreamingChangeEventSource$$Lambda$1016/10641269@12fef255,com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@18c84a61,com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@55443f, lifecycleListeners(5): com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@61540cca,com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@352b5758,io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener@730a6982,com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@18c84a61,com.github.shyiko.mysql.binlog.jmx.BinaryLogClientStatistics@55443f
```

We believe, the imporper use of mysql BinlogClient is the root cause of some task hung up issues, such as #1156。

### CODE REVIEW

**Comment by lzshlzsh** [comment]
@leonardBang @kylemeow @minchowang Would you help to look at this problem.

**Comment by lzshlzsh** [comment]
We just encountered this problem online. The snapshot stage is stuck, and the problem is solved after this repair. @minchowang

**Comment by yuxiqian** [comment]
Hi @lzshlzsh, thanks for your contribution! Before this PR could be merged, could you please rebase it with latest `master` branch?

cc @leonardBang @PatrickRen

**Comment by suxinglee** [comment]
@yuxiqian need attention

**Comment by misaya295** [comment]
@yuxiqian Is it fix in order pr? I cant find this code in flink-cdc master

**Comment by yuxiqian** [comment]
Hi Misaya, it seems the original author of this PR has been inactive for a long time, and this PR is way off HEAD branch and not ready for merge. Feel free to open another PR for this if it's still reproducible in the latest version. :)

**Pull request closed without merging**
