### PR TITLE
[mysql] keep order of each split by replacing HashMap with LinkedHashMap

### PR DESCRIPTION
**Pull request by yujiaxinlong**
#1074 

When creating normalizedSplitRecords in RecordUtils, original order of records are lost because the use of HashMap. 
Since the order might be useful in some occasion, it's better to replace HashMap with LinkedHashMap to keep the order.

There is no big efficiency difference between HashMap and LinkedHashMap, so there seems no need to have a new property to config this.

### CODE REVIEW

**Comment by yujiaxinlong** [comment]
@leonardBang  can you review this  PR?

**Comment by ruanhang1993** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/1231 has changed this part of code. You need to rebase master branch.

**Comment by yujiaxinlong** [comment]
> #1231 has changed this part of code. You need to rebase master branch.

thanks， just resolved it. 

can you help rerun the checks, the errors seems irrelevent

**Comment by yuxiqian** [comment]
Hi @yujiaxinlong, sorry for the delay of this PR. Could you please rebase it to latest `master` branch since there’s been lots of changes in Flink CDC repo since your original commit? Kindly reminder that `com.ververica.cdc.connectors.mysql` package has been moved to `org.apache.flink.cdc.connectors.mysql`.

Thanks for your contribution!

**Pull request closed without merging**
