### PR TITLE
[mysql-cdc] Current binlog offset add serverId, fix incremental-snapshot scan data lose

### PR DESCRIPTION
**Pull request by EchoLee5**
Current binlog offset add serverId, fix incremental-snapshot scan data lose
link https://github.com/ververica/flink-cdc-connectors/issues/2794

### CODE REVIEW

**Review by ruanhang1993 — COMMENTED** [review]
@EchoLee5 Thanks for the fix. Could you add some tests to cover this bug? 
I think we could start a mysql container without `gtid-mode = on` to reproduce this bug.

**Comment by ruanhang1993** [comment]
The problem will occur when the gtid mode is closed and some data changes happen in the snapshot phase.

**Comment by EchoLee5** [comment]
> The problem will occur when the gtid mode is closed and some data changes happen in the snapshot phase.

Sorry for being late, I have added unit tests, please review them for me, thank you!

**Comment by yuxiqian** [comment]
Hi @EchoLee5, could you please rebase this PR with latest `master` branch before it could be merged?

cc @ruanhang1993

**Pull request closed without merging**
