### PR TITLE
[hotfix] Modify the schema and table name snapshot data reading probl…

### PR DESCRIPTION
**Pull request by code-dm**
Modify the schema and table name snapshot data reading problem with the same name.
For example:
I want to get data from databaseName: test1 schemaName: dbo tableName: fl_test, but my master database has the same schema and table, it will have exception.

### CODE REVIEW

**Comment by ruanhang1993** [comment]
@code-dm Thanks for contribution. There is already a PR #2160 to fix this.

**Comment by ruanhang1993** [comment]
Could you help to review that PR? Thanks~

**Comment by code-dm** [comment]
@ruanhang1993 I found this PR #2160 for a MySQL database modification，This PR of mine is for SqlServer.
Or I think it is possible to rewrite a PR to solve this problem for all databases.

**Comment by yuxiqian** [comment]
Hi @code-dm, thanks for your contribution! Could you please rebase this PR with latest `master` branch before it could be merged?

**Pull request closed without merging**
