### PR TITLE
[BP-3.1][FLINK-35323][runtime] Fix transform failure when one rule matches multiple schemas

### PR DESCRIPTION
**Pull request by yuxiqian**
This closes FLINK-35323.

Currently, Transform module doesn’t support handling multiple tables with different schema within one projection / filtering rule. This is not intended and turns out to be related to incorrectly handled processor caching strategy. Fixing the cache key should resolve this problem.

### CODE REVIEW

**Comment by yuxiqian** [comment]
cc @aiwenmo

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by yuxiqian** [comment]
Could @PatrickRen help take a look? Thanks!

**Review by leonardBang — APPROVED** [review]
Thanks @yuxiqian for the fix, LGTM

**Pull request merged**
