### PR TITLE
[docs]Problem with Case Document Format in Quickstart

### PR DESCRIPTION
**Pull request by ZmmBigdata**
There is an issue with the format of three shell scripts
cf9c895cc2a90e65946ffd620217f48
cc29af05deb1f5d2ddc47d46121de42
498cef1ec5bc541d790643753af0874

### CODE REVIEW

**Review by yuxiqian — APPROVED** [review]
Thanks for @ZmmBigdata's contribution! Pulled, built docs locally and it looks good.

**Comment by Jiabao-Sun** [comment]
Thanks @ZmmBigdata for this contribution.
Could you rebase master and resolve conflicts?

**Comment by ZmmBigdata** [comment]
> @ZmmBigdata @Jiabao-Sun Issue was fixed in pr #3217 and merged.

@GOODBOY008 In PR # 3217, only two files were modified, while I modified three files

**Comment by ZmmBigdata** [comment]
@GOODBOY008 Do I need to resynchronize the master repositories and resubmit the PR?

**Comment by Jiabao-Sun** [comment]
@ZmmBigdata yes, please go ahead.

**Comment by Jiabao-Sun** [comment]
Hi @ZmmBigdata, you don't need submit a new PR.
Just rebase the master branch into yours.

**Comment by ZmmBigdata** [comment]
> Hi @ZmmBigdata, you don't need submit a new PR. Just rebase the master branch into yours.

@Jiabao-Sun Ok, thank you for your reply. Will this PR still be merged？Not very familiar with this process.

**Comment by Jiabao-Sun** [comment]
> > Hi @ZmmBigdata, you don't need submit a new PR. Just rebase the master branch into yours.
> 
> @Jiabao-Sun Ok, thank you for your reply. Will this PR still be merged？Not very familiar with this process.

Yes

**Pull request closed without merging**
