### PR TITLE
[hotfix] Change old com.ververica dependency to flink

### PR DESCRIPTION
**Pull request by xleoken**
Change old com.ververica dependency to flink. Follow up https://github.com/apache/flink-cdc/pull/3089

### CODE REVIEW

**Comment by xleoken** [comment]
cc @leonardBang

**Comment by lvyanquan** [comment]
Hi @xleoken, Can you update [flink-cdc.sh](https://github.com/apache/flink-cdc/blob/master/flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh#L73) too?

**Comment by xleoken** [comment]
> Hi @xleoken, Can you update [flink-cdc.sh](https://github.com/apache/flink-cdc/blob/master/flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh#L73) too?

Make sense, updated.

**Comment by lvyanquan** [comment]
@xleoken Hi，I‘ve merged one pr https://github.com/apache/flink-cdc/pull/3118/files and introduced one more package, can you rebase master and include it?

**Comment by xleoken** [comment]
> Make sense, updated.

Make sense, updated.

**Comment by xleoken** [comment]
@PatrickRen PTAL

**Comment by xleoken** [comment]
cc @leonardBang @PatrickRen @Jiabao-Sun

**Comment by xleoken** [comment]
cc @leonardBang @PatrickRen @Jiabao-Sun

**Comment by xleoken** [comment]
cc @leonardBang @PatrickRen @Jiabao-Sun

**Review by PatrickRen — APPROVED** [review]
@xleoken Thanks for the PR! LGTM.

**Comment by PatrickRen** [comment]
@xleoken Could you open another PR to backport the patch to release-3.0 branch? Thanks

**Comment by xleoken** [comment]
Thanks @PatrickRen.

> Could you open another PR to backport the patch to release-3.0 branch? Thanks

We can not chang the pom.xml files in release-3.0 branch directly.

image

**Comment by PatrickRen** [comment]
@xleoken Ah my mistake. We don't need to backport this one to release-3.0 as 3.1 will be the first version after the donation. Thanks anyway!

**Pull request merged**
