### PR TITLE
[FLINK-35291] Improve the ROW data deserialization performance of DebeziumEventDeserializationScheme

### PR DESCRIPTION
**Pull request by lzshlzsh**
#flink-35291

### CODE REVIEW

**Comment by lzshlzsh** [comment]
@ruanhang1993 Would you help have a look at this?

**Comment by Myasuka** [comment]
@lzshlzsh What's the performance gain (or throughput improve) with this patch?

**Review by lvyanquan — APPROVED** [review]
LGTM. Thanks for it.

**Comment by lvyanquan** [comment]
@ruanhang1993 @leonardBang  CC.

**Comment by lzshlzsh** [comment]
> @lzshlzsh What's the performance gain (or throughput improve) with this patch?
Sorry for the late reply. According to my testing, there is approximately a 40% performance improvement (3.5w/s ->5w/s). 
see [flink-35291](https://issues.apache.org/jira/browse/FLINK-35291)

**Review by yuxiqian — APPROVED** [review]
Looks reasonable to me, cc @leonardBang

**Review by ruanhang1993 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
