### PR TITLE
[FLINK-35592] Fix MysqlDebeziumTimeConverter miss timezone convert to timestamp

### PR DESCRIPTION
**Pull request by czy006**
Fix [FLINK-35173](https://issues.apache.org/jira/browse/FLINK-35173) MysqlDebeziumTimeConverter miss timezone convert to timestamp.

### CODE REVIEW

**Comment by yuxiqian** [comment]
Hi @czy006, could you please open another PR to backport this patch to `release-3.1` branch?

**Review by leonardBang — COMMENTED** [review]
@czy006 Thanks for the contribution, could you add a test for the change?

**Comment by leonardBang** [comment]
@czy006 Could you help rebase this PR？

**Review by leonardBang — APPROVED** [review]
+1, CI passed, merging...

**Pull request merged**
