### PR TITLE
[FLINK-35544][minor][docs] Add deployment documentations for Kubernetes Operator.

### PR DESCRIPTION
**Pull request by qg-lin**
https://issues.apache.org/jira/browse/FLINK-35544

### CODE REVIEW

**Comment by leonardBang** [comment]
Thanks for the contributiion @qg-lin , could you create a FLINK JIRA and link it? it will be great if you can add some description for this PR

**Comment by qg-lin** [comment]
JIRA: https://issues.apache.org/jira/browse/FLINK-35544

**Comment by qg-lin** [comment]
> Thanks for the contributiion @qg-lin , could you create a FLINK JIRA and link it? it will be great if you can add some description for this PR


> Thanks for the contributiion @qg-lin , could you create a FLINK JIRA and link it? it will be great if you can add some description for this PR

Done!

**Review by PatrickRen — APPROVED** [review]
@qg-lin Thanks for the contribution! LGTM

**Comment by BjarkeTornager** [comment]
Just fell over this PR when looking into whether Flink CDC works with the Flink Kubernetes Operator. @qg-lin any reason why this PR has not been merged yet?

**Comment by leonardBang** [comment]
I guess @PatrickRen forgot this PS， will merge soon

**Comment by qg-lin** [comment]
> @qg-lin would you like to open a PR for branch `release-3.2`?

sure

**Pull request merged**
