### PR TITLE
Release 2.4

### PR DESCRIPTION
**Pull request by lizhongze1**
[db] When modifying the time zone connection parameters in the database, the last connection information is still used (#2590)

### CODE REVIEW

**Comment by leonardBang** [comment]
@lizhongze1 I do not understand the purpose of this PR, could you explain more ?

**Comment by lizhongze1** [comment]
1、在flink的standalone模式下创建mysql任务：传入数据库ip、用户名、密码、时区等信息启动同步任务
2、停止任务
3、修改刚才传入的mysql时区信息（其他参数不变）

此时在数据库缓存池信息不会销毁，导致使用的还是第一次创建的信息（其他数据库同理）

**Comment by leonardBang** [comment]
Thanks @lizhongze1 for the contribution,I cannot understand the PR purpose from  the PR description `Release 2.4` , could you change it and you should use `git rebase` when open a PR which will only introduce your own commits

**Comment by yuxiqian** [comment]
Closing this PR since it has been outdated. Please reopen a PR for this patch.

**Pull request closed without merging**
