### PR TITLE
[cdc-connector][sqlserver]Flink cdc pipeline support sqlserver source

### PR DESCRIPTION
**Pull request by ChengJie1053**
Flink cdc pipeline support sqlserver source
image

image

image

### CODE REVIEW

**Comment by cobolbaby** [comment]
Is there anyone who can help review this?

**Comment by zakhalex** [comment]
@ChengJie1053 - I have opened a pull request to your master branch, as well as to apache master branch with a list of fixes and changes to the code your proposed - my pull request to apache is https://github.com/apache/flink-cdc/pull/3507 and my pull to your master is https://github.com/ChengJie1053/flink-cdc/pull/1

**Review by zakhalex — APPROVED** [review]

**Comment by zakhalex** [comment]
@ChengJie1053 - do you have the privilege to approve the workflows?

**Comment by ChengJie1053** [comment]
> @ChengJie1053 - do you have the privilege to approve the workflows?

I'm sorry. I don't have that clearance

**Comment by lvyanquan** [comment]
@ChengJie1053 Add some ITCases to help verify the correctness of the code will be better.

**Comment by ChengJie1053** [comment]
> @ChengJie1053 Add some ITCases to help verify the correctness of the code will be better.

Okay, thank you. I'll add test cases later

**Comment by cobolbaby** [comment]
Why is a perfectly good PR being ignored?

**Comment by lvyanquan** [comment]
> Why is a perfectly good PR being ignored?

Yeah, I think we should add this to our roadmap in next or two major version, @ChengJie1053 do you have time to continue complete it?

**Comment by ChengJie1053** [comment]
Sorry, I will finish this work as soon as possible, I am a little busy at the moment, I will spare some time later

**Comment by arielmoraes** [comment]
Is there any news on this?

**Comment by arielmoraes** [comment]
@ChengJie1053 will you work on this again?

**Comment by cobolbaby** [comment]
@ChengJie1053 will you work on this again?

**Comment by durlabhjain** [comment]
Any idea if this is planned to be resolved?

**Pull request closed without merging**
