### PR TITLE
[docs] Rectify names of CDC sources for Flink

### PR DESCRIPTION
**Pull request by yuxiqian**
Since Flink CDC 3.0 release, pipeline connectors are now first-class citizens. At the same time, all previous connectors designed for Flink are classified as "legacy" connectors, which is misleading since they're still under active development and improvement, and there's no plan to drop support for them.

This PR rectifies the term from "Legacy CDC Sources" to "Flink Sources" in CDC documentations, and refactored doc tree as follows:

```
connectors
├── Pipeline Connectors
│   ├── Overview
│   ├── MySQL
│   ├── Paimon
│   ├── Kafka
│   ├── Doris
│   └── StarRocks
└── Flink Sources
    ├── Overview
    ├── MySQL
    ├── Oracle
    ├── SQL Server
    ├── PostgreSQL
    ├── MongoDB
    ├── Db2
    ├── TiDB
    ├── OceanBase
    ├── Vitess
    └── Tutorials
```

### CODE REVIEW

**Comment by yuxiqian** [comment]
@leonardBang @GOODBOY008 PTAL

**Comment by leonardBang** [comment]
Thanks @yuxiqian for the contribution, could we put the pipeline-connectors to the first place?

**Comment by yuxiqian** [comment]
@leonardBang Sure, reordered sidebar items based on DB-Engine Rankings.

**Comment by leonardBang** [comment]
> @leonardBang Sure, reordered sidebar items based on DB-Engine Rankings.

Thanks for the update and basing on DB-Engine Ranking makes sense to me

**Review by leonardBang — APPROVED** [review]
Thanks @yuxiqian for the contribution, LGTM

**Comment by leonardBang** [comment]
@yuxiqian Will appreciate if you can also open PR for release-3.0 and release-3.1 branches.

**Comment by yuxiqian** [comment]
@leonardBang Seems I missed some `{{ref}}` hyperlinks. Will fix it first.

**Comment by ysmintor** [comment]
Yes, I agree this refactoring. And is there any plan to add support Oracle, PostgreSQL, OceanBase, etc into pipeline connectors ?

**Pull request merged**
