### PR TITLE
[FLINK-36681][mysql-cdc][doc] Fix the wrong chunks splitting query in incremental snapshot reading section

### PR DESCRIPTION
**Pull request by herunkang2018**

### CODE REVIEW

**Review by leonardBang — APPROVED** [review]
+1

**Comment by leonardBang** [comment]
@herunkang2018 Would you like to open a PR for release-3.2 branch ?

**Comment by herunkang2018** [comment]
@leonardBang Yes, I will backport it to release-3.2 branch soon.

**Comment by herunkang2018** [comment]
The backport PR is ready: https://github.com/apache/flink-cdc/pull/3732

**Pull request merged**
