### PR TITLE
[FLINK-36678][docs][deploy] Fixed the documentation error of Flink CDC YARN deployment mode

### PR DESCRIPTION
**Pull request by Timi988**
In the Yarn deployment mode of the Flink CDC document, there is an error in the document description. The original text was' submit job to Flink standalone cluster using Cli ', but the correct version should be' submit job to Flink Yarn Session Cluster using Cli '

### CODE REVIEW

**Review by Shawn-Hx — APPROVED** [review]
LGTM

**Review by leonardBang — APPROVED** [review]
+1, thanks @Timi988 for the fix

**Comment by Timi988** [comment]
> +1, thanks @Timi988 for the fix

Thank you for your affirmation , is there anything else needed to get this merged @leonardBang

**Comment by leonardBang** [comment]
@Timi988 Would you like to open a PR for release-3.2 branch?

**Comment by Timi988** [comment]
> @Timi988 Would you like to open a PR for release-3.2 branch?

Okay

**Pull request merged**
