### PR TITLE
[FLINK-34184] Update copyright and license file

### PR DESCRIPTION
**Pull request by ruanhang1993**
This PR updates copyright for each file and license file.

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Thanks @ruanhang1993 for this update.

Shall we change the NOTICE and site/NOTICE file as well?
https://github.com/apache/flink-cdc/blob/f7fa3175809b4b912b19ad91c89599bf1c2b9ea3/NOTICE#L1-L3

Some files in the docs directory, such as Dockerfile, make.bat, site/index.html, appear to be missing a license header.

**Comment by ruanhang1993** [comment]
> Thanks @ruanhang1993 for this update.
> 
> Shall we change the NOTICE and site/NOTICE file as well?
> 
> https://github.com/apache/flink-cdc/blob/f7fa3175809b4b912b19ad91c89599bf1c2b9ea3/NOTICE#L1-L3
> 
> Some files in the docs directory, such as Dockerfile, make.bat, site/index.html, appear to be missing a license header.

We have a different issue(https://issues.apache.org/jira/browse/FLINK-34183) to change the LICENSE files. I will raise another PR to change it.

**Review by Jiabao-Sun — APPROVED** [review]

**Comment by ruanhang1993** [comment]
@Jiabao-Sun @leonardBang , the header of some files are not changed.

1. termynal.css and termynal.js have the following header.
```
/**
 * termynal.js
 *
 * @author Ines Montani <ines@ines.io>
 * @version 0.0.1
 * @license MIT
 */
```

2. The classes we copied from the debezium have the following header:
```
/*
 * Copyright Debezium Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
```

I am not sure how to change their headers. WDYT?

**Comment by leonardBang** [comment]
> @Jiabao-Sun @leonardBang , the header of some files are not changed.
> 
> 1. termynal.css and termynal.js have the following header.
> 
> ```
> /**
>  * termynal.js
>  *
>  * @author Ines Montani <ines@ines.io>
>  * @version 0.0.1
>  * @license MIT
>  */
> ```
> 
> 2. The classes we copied from the debezium have the following header:
> 
> ```
> /*
>  * Copyright Debezium Authors.
>  *
>  * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
>  */
> ```
> 
> I am not sure how to change their headers. WDYT?

I think we should keep current header.

**Review by leonardBang — APPROVED** [review]
Thanks @ruanhang1993 for the huge PR, LGTM

**Pull request merged**
