### PR TITLE
[FLINK-34959] Update old flink-cdc-connectors artifactId

### PR DESCRIPTION
**Pull request by xleoken**
Update old `flink-cdc-connectors` artifactId to `flink-cdc`.

image

### CODE REVIEW

**Comment by laglangyue** [comment]
lgtm

**Review by czy006 — APPROVED** [review]
LGTM

**Comment by xleoken** [comment]
cc @Jiabao-Sun

**Comment by xleoken** [comment]
cc @Jiabao-Sun @PatrickRen

**Review by PatrickRen — APPROVED** [review]
@xleoken Thanks for the patch! LGTM

**Pull request merged**
