### PR TITLE
[Bug][Oracle] oracle 单表全量阶段根据ROWID 字段 split chunk存在BUG

### PR DESCRIPTION
**Pull request by zhaomin1423**
close https://github.com/ververica/flink-cdc-connectors/issues/2296#issue-1802089759

### CODE REVIEW

**Comment by zhaomin1423** [comment]
Could you like to test it using your table and data, I can't reproduce it. @nidonglin

**Comment by zhaomin1423** [comment]
cc @ruanhang1993 @leonardBang

**Comment by nidonglin** [comment]
> Could you like to test it using your table and data? I can't reproduce it. @nidonglin

I've tested it, and it's true in my test case

**Comment by zhaomin1423** [comment]
> > Could you like to test it using your table and data? I can't reproduce it. @nidonglin
> 
> I've tested it, and it's true in my test case

Thank you very much.

**Comment by gong** [comment]
@zhaomin1423 Hello, How to prove this ROWIDcomparison method is correct or is consistent with oracle database comparison method?

**Comment by yuxiqian** [comment]
Hi @zhaomin1423, could you please rebase with latest `master` branch before further actions? Thanks for your contribution!

**Pull request closed without merging**
