### PR TITLE
[FLINK-34908][pipeline-connector][starrocks] Fix MySQL to doris pipeline will lose precision for timestamp type 

### PR DESCRIPTION
**Pull request by ChengJie1053**
https://github.com/apache/flink-cdc/pull/3207

I found this code while learning the flink cdc source code, I think starrocks may have similar problems, if this piece has been done, I will close the pr

### CODE REVIEW

**Comment by yuxiqian** [comment]
Thanks for @ChengJie1053's great work, could you please add some test cases to verify this change? Also some existed testcases might need to be tweaked to reflect this change:

```diff
Error:  Failures: 
Error:    EventRecordSerializationSchemaTest.testMixedSchemaAndDataChanges:133->verifySerializeResult:275

+expected:<{__op=0, col1=1, col2=true, col3=2023-11-27 18:00:00}>
- but was:<{__op=0, col1=1, col2=true, col3=2023-11-27 18:00:00.000000}>
```

**Comment by ChengJie1053** [comment]
> Thanks for @ChengJie1053's great work, could you please add some tests to verify this change? Also some existing testcases might need to be tweaked to reflect this change:
> 
> ```diff
> Error:  Failures: 
> Error:    EventRecordSerializationSchemaTest.testMixedSchemaAndDataChanges:133->verifySerializeResult:275
> 
> +expected:<{__op=0, col1=1, col2=true, col3=2023-11-27 18:00:00}>
> - but was:<{__op=0, col1=1, col2=true, col3=2023-11-27 18:00:00.000000}>
> ```

Ok, thanks for reviewing the code for me

**Comment by gong** [comment]
@ChengJie1053 https://issues.apache.org/jira/projects/FLINK/issues/FLINK-34908?filter=allissues Hello, I found starrocks only support second level precision, so I did't modify starrocks pipeline. I added comment in issue. You can visit link https://docs.starrocks.io/zh/docs/sql-reference/data-types/date-types/DATETIME/

**Comment by ChengJie1053** [comment]
> @ChengJie1053 https://issues.apache.org/jira/projects/FLINK/issues/FLINK-34908?filter=allissues Hello, I found starrocks only support second level precision, so I did't modify starrocks pipeline. I added comment in issue. You can visit link https://docs.starrocks.io/zh/docs/sql-reference/data-types/date-types/DATETIME/

Okay, thank you. Thank you for your guidance

**Pull request closed without merging**
