### PR TITLE
[mysql] Mysql-cdc adapt mariadb.

### PR DESCRIPTION
**Pull request by ThisisWilli**
This PR fixed [2398](https://github.com/ververica/flink-cdc-connectors/issues/2398)

### CODE REVIEW

**Comment by ThisisWilli** [comment]
PTAL @ruanhang1993 @leonardBang ~

**Comment by leonardBang** [comment]
Thanks @ThisisWilli for the great work, add to my TODO list now.

**Comment by yuxiqian** [comment]
Hi @ThisisWilli, thanks for your great contribution! Could you please rebase this PR with latest `master` branch? You may need to rename some packages like from `com.ververica.cdc` to `org.apache.flink.cdc`.

cc @leonardBang

**Comment by ThisisWilli** [comment]
> Hi @ThisisWilli, thanks for your great contribution! Could you please rebase this PR with latest `master` branch? You may need to rename some packages like from `com.ververica.cdc` to `org.apache.flink.cdc`.
> 
> cc @leonardBang

@yuxiqian I'll find time to finish this work in mid-May.

**Comment by linmingze** [comment]
hello 
en how about this fix going

**Comment by ThisisWilli** [comment]
> hello en how about this fix going

still in progress now, maybe finish in the end of June.

**Comment by leonardBang** [comment]
@ThisisWilli Would you like to continue work for this PR？

**Pull request closed without merging**
