### PR TITLE
[FLINK-35527][docs] Polish quickstart guide & migrate maven links from ververica to apache

### PR DESCRIPTION
**Pull request by yuxiqian**
This PR:

* Adds guide to provide excluded DB drivers in quickstart docs
* Updates outdated maven jar links & move to `org.apache.flink` group ID

### CODE REVIEW

**Review by morazow — APPROVED** [review]
Thanks @yuxiqian!

Verified the links, looks good 👍

**Comment by gtk96** [comment]
cc @Jiabao-Sun @GOODBOY008

**Review by Jiabao-Sun — COMMENTED** [review]
Thanks @yuxiqian for this contribution.
How about open a jira issue to link this PR?

**Review by Jiabao-Sun — APPROVED** [review]
LGTM.

**Pull request merged**
