### PR TITLE
Update OracleSourceBuilder's constructor to private

### PR DESCRIPTION
**Pull request by zhaomin1423**

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@zhaomin1423 Please update `SqlServerSourceBuilder` too.

**Comment by zhaomin1423** [comment]
Updated, thanks.





---- Replied Message ----
| From | ***@***.***> |
| Date | 07/25/2023 14:09 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ververica/flink-cdc-connectors] Update OracleSourceBuilder's constructor to private (PR #2327) |

@zhaomin1423 Please update SqlServerSourceBuilder too.

**Comment by zhaomin1423** [comment]
Could you help me review it? @GOODBOY008 @leonardBang @ruanhang1993

**Comment by yuxiqian** [comment]
Thanks @zhaomin1423 for the great work! Before this PR could be merged, could you please rebase it with latest `master` branch?

**Pull request closed without merging**
