### PR TITLE
[FLINK-36407] Shut down coordinatorExecutor upon closing SchemaRegistry

### PR DESCRIPTION
**Pull request by morozov**
See the details in [FLINK-36407](https://issues.apache.org/jira/browse/FLINK-36407). Not sure how this can be unit-tested given that the issue is not reproducible with JUnit.

### CODE REVIEW

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Comment by morozov** [comment]
The MongoDB test failure looks irrelevant:
```
java.net.SocketException: Connection reset
 	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_422]
 	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_422]
 	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:175) ~[mongodb-driver-core-4.11.2.jar:?]
 	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:200) ~[mongodb-driver-core-4.11.2.jar:?]
 	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:739) ~[mongodb-driver-core-4.11.2.jar:?]
 	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:603) ~[mongodb-driver-core-4.11.2.jar:?]
 	... 10 more
```

**Comment by morozov** [comment]
@ruanhang1993 is there anything else needed to get this merged?

**Review by lvyanquan — APPROVED** [review]
LGTM.

**Review by ruanhang1993 — APPROVED** [review]
LGTM.

**Pull request merged**
